### ISSUE TITLE
question about kernel tree

### ISSUE THREAD

**Issue by Desperatesonic** [EngineeringSoftware/roosterize#9]
hello! I am really interested in the "tree chopping" methods mentioned in your paper. However I know very little about the internal data structures of Coq, I wonder is there any documentation easy to read about this?
for example, when I use coq_serapi to input :
forall xyz:nat, xyz<3
I got output:
(Prod (Name (Id xyz)) (Ind (((Mutind (MPfile (DirPath ((Id Datatypes) (Id Init) (Id Coq)))) (DirPath ()) (Id nat)) 0) (Instance ()))) (App (Const ((Constant (MPfile (DirPath ((Id Peano) (Id Init) (Id Coq)))) (DirPath ()) (Id lt)) (Instance ()))) ((Rel 1) (App (Construct ((((Mutind (MPfile (DirPath ((Id Datatypes) (Id Init) (Id Coq)))) (DirPath ()) (Id nat)) 0) 2) (Instance ()))) ((App (Construct ((((Mutind (MPfile (DirPath ((Id Datatypes) (Id Init) (Id Coq)))) (DirPath ()) (Id nat)) 0) 2) (Instance ()))) ((App (Construct ((((Mutind (MPfile (DirPath ((Id Datatypes) (Id Init) (Id Coq)))) (DirPath ()) (Id nat)) 0) 2) (Instance ()))) ((Construct ((((Mutind (MPfile (DirPath ((Id Datatypes) (Id Init) (Id Coq)))) (DirPath ()) (Id nat)) 0) 1) (Instance ()))))))))))))
This looks so terrifying! I really wonder about the meanings of Mutind, MPfile and Rel blablabla....
So I can better understand what parts of the kernel tree is important for information extraction.
looking forward to your reply, thanks a lot!

**Comment by pengyunie** [comment]
Hi,

Unfortunately there is no documentation for that (in SerAPI) as far as I know :(  I'd suggest searching for those terms in [SerAPI repo](https://github.com/ejgallego/coq-serapi) to find their definitions and guess their meanings.

You could also refer to what we extracted in our tree chopping heuristics (see details in our [code](https://github.com/EngineeringSoftware/roosterize/blob/master/roosterize/data/LemmaBackendSexpTransformers.py#L22-L149) and [documentation](https://github.com/EngineeringSoftware/roosterize/blob/master/roosterize/data/LemmaBackendSexpTransformers.py#L8-L16)).

Hope these help. Thanks!

**Comment by sonic202607** [comment]
Thanks for your help！By the way, I also wonder how you get the syntax tree by serAPI. I know we can get kernel tree and lemma sentence by querying PpSer and PpStr. But I don't see what is the syntax tree and how to get it. Could you shed some more lights on this?

**Comment by pengyunie** [comment]
The "syntax tree" is literally the abstract syntax tree of the lemma. For example:

```
Lemma mg_eq_proof L1 L2 (N1 : mgClassifier L1) : L1 =i L2 -> nerode L2 N1. 
```
has the following syntax tree:
```
(VernacExpr()(VernacStartTheoremProof Lemma (Id mg_eq_proof)
(((CLocalAssum(Name(Id L1))(CHole()IntroAnonymous()))
(CLocalAssum(Name(Id L2))(CHole()IntroAnonymous()))
(CLocalAssum(Name(Id N1))
(CApp(CRef(Ser Qualid(DirPath())(Id mgClassifier)))(CRef(Ser Qualid(DirPath())(Id L1))))))
(CNotation(InConstrEntrySomeLevel" -> ")
(CNotation(InConstrEntrySomeLevel" =i ")
(CRef(Ser Qualid(DirPath())(Id L1)))(CRef(Ser Qualid(DirPath())(Id L2))))
(CApp(CRef(Ser Qualid(DirPath())(Id nerode)))
(CRef(Ser Qualid(DirPath())(Id L2)))(CRef(Ser Qualid(DirPath())(Id N1))))))))
```

I obtained them from SerAPI using the following command (this command prints the syntax tree of the entire file, and I extracted the parts corresponding to the lemmas):
```
sercomp {serapi_options} --mode=sexp -- {coq_file}
```

**Comment by sonic202607** [comment]
thanks a lot for your help! I didnt know that command before

**Comment by palmskog** [comment]
@Desperatesonic The best documentation for kernel trees is likely the [Coq source code](https://github.com/coq/coq/blob/v8.10/kernel/constr.mli#L207-L236). There, `Prod`, `App`, and similar constant names are listed. For low-level technical reasons, we don't use exactly the core kernel tree definition in Roosterize but something very close. Essentially, what SerAPI does is make these OCaml datatypes defined by Coq developers serializable via metaprogramming (i.e., the code introspects on the OCaml definition to provide textual versions). You will not find the names of constants in SerAPI itself, typically.

All we do using the CLI programs `sercomp`, `sername`, `sertok` can be done directly by interacting with the SerAPI library API. Essentially, the serialization of abstract syntax trees just sets up a loop that feeds Coq sentences to Coq via SerAPI and outputs the serialized results; the key file is [sercomp.ml](https://github.com/ejgallego/coq-serapi/blob/v8.10/sertop/sercomp.ml).

For another approach to using SerAPI, see [Alectryon](https://github.com/cpitclaudel/alectryon), a document processor which does all the querying of SerAPI in Python.

**Comment by sonic202607** [comment]
@palmskog thank you, this completely answered my question!

**Comment by palmskog** [comment]
@Desperatesonic another not so obvious point: the default kernel tree in Coq uses [de Bruijn indices](https://en.wikipedia.org/wiki/De_Bruijn_index) to handle bound names (this is the `Rel 1` in your example above). This means that all semantic information in variable names added by a user has been thrown away and replaced with numbers. To use variable names in learning, we make sure to avoid de Bruijn indices, and SerAPI provides options to do this.

**Comment by sonic202607** [comment]
@palmskog  thanks for your reminding me!
